import { useMemo } from "react";
import { UserLevel, ProgramObjective } from "@/generated/prisma";
import type {
  ProgramInsightsData,
  MuscleDetailedMetrics,
  MuscleRecommendation,
  ExerciseMetrics,
  BaseInsightsParams,
} from "./insights/types";
import { getGrade, getStatus, InsightStatus } from "./insights/types";

/**
 * All these hooks now use the criteria-based evaluation system
 */
import { useVolumeInsights } from "./insights/use-volume-insights"; // Uses volume-criteria.ts
import { useFrequencyInsights } from "./insights/use-frequency-insights"; // Uses frequency-criteria.ts
import { useExerciseBalanceInsights } from "./insights/use-exercise-balance-insights"; // Uses exercise-balance-criteria.ts
import { useIntensityInsights } from "./insights/use-intensity-insights";
import { useRecoveryInsights } from "./insights/use-recovery-insights";
import { useIntensityTechniquesInsights } from "./insights/use-intensity-techniques-insights";

/**
 * CRITERIA-BASED INSIGHTS SYSTEM
 *
 * This hook aggregates insights from multiple categories, each using the
 * criteria-based evaluation system for scoring and recommendations.
 *
 * Architecture:
 * 1. Each category (volume, frequency, exercise balance) has its own hook
 * 2. Each hook uses criteria evaluators (see insights/*-criteria.ts files)
 * 3. Criteria are evaluated and scores are aggregated with configurable weights
 * 4. Recommendations are automatically generated by criteria with low scores
 *
 * Benefits:
 * - Easy to add new criteria (just create a new evaluator function)
 * - Configurable weights for each criterion
 * - Can enable/disable criteria without code changes
 * - Consistent pattern across all insight categories
 *
 * To add a new criterion:
 * 1. Create evaluator in insights/*-criteria.ts
 * 2. Add to config array in insights/use-*-insights.ts
 * 3. Pass required data to the hook
 */

// Helper to determine priority based on score
function getPriority(score: number): "high" | "medium" | "low" {
  if (score < 50) return "high";
  if (score < 70) return "medium";
  return "low";
}

// Helper to calculate category score
function calculateCategoryScore(scores: number[]): number {
  if (scores.length === 0) return 0;
  return scores.reduce((sum, score) => sum + score, 0) / scores.length;
}

/**
 * Main hook that aggregates all program insights
 *
 * @param program - The program with full session data
 * @param activeSessionId - Currently active session (for form preview)
 * @param activeSessionFormValues - Form values for active session
 * @param currentWeek - Week number to analyze
 * @param userLevel - User's training level (Beginner, Intermediate, Advanced, Elite)
 * @param objective - Program objective (Hypertrophy, Strength, PowerLifting, Endurance)
 * @returns Complete program insights with scores, recommendations, and metrics
 */
export const useProgramInsights = ({
  program,
  activeSessionId,
  activeSessionFormValues,
  currentWeek = 1,
  userLevel: userLevelProp,
  objective: objectiveProp,
}: BaseInsightsParams): ProgramInsightsData => {
  const userLevel = userLevelProp || UserLevel.Intermediate;
  const objective =
    objectiveProp || program.objective || ProgramObjective.Hypertrophy;

  const volumeMetrics = useVolumeInsights({
    program,
    activeSessionId,
    activeSessionFormValues,
    currentWeek,
    userLevel,
    objective,
  });

  const frequencyMetrics = useFrequencyInsights({
    program,
    activeSessionId,
    activeSessionFormValues,
    currentWeek,
    userLevel,
  });

  const exerciseBalance = useExerciseBalanceInsights({
    program,
    activeSessionId,
    activeSessionFormValues,
    currentWeek,
    userLevel,
    objective,
  });

  const intensityMetrics = useIntensityInsights({
    program,
    activeSessionId,
    activeSessionFormValues,
    currentWeek,
  });

  const recoveryMetrics = useRecoveryInsights({
    program,
    activeSessionId,
    activeSessionFormValues,
    currentWeek,
  });

  const intensityTechniques = useIntensityTechniquesInsights({
    program,
    activeSessionId,
    activeSessionFormValues,
    currentWeek,
  });

  return useMemo(() => {
    /**
     * CRITERIA-BASED SCORING SYSTEM
     *
     * All scores are now calculated using the criteria evaluation system:
     *
     * - Volume: Uses evaluateBaseVolume (volume-criteria.ts)
     *   Score is based on MEV/MAV/MRV ranges
     *
     * - Frequency: Uses multiple criteria (frequency-criteria.ts)
     *   - evaluateBaseFrequency (90% weight)
     *   - evaluateFrequencyDistribution (10% weight, disabled)
     *   Final score is weighted average of enabled criteria
     *
     * - Recovery: Uses multiple criteria (recovery-criteria.ts)
     *   - evaluateConsecutiveDays (100% weight)
     *
     * - Exercise Balance: Uses evaluateCompoundIsolationRatio (exercise-balance-criteria.ts)
     *   Score is based on deviation from ideal compound/isolation ratio
     */

    // Calculate average scores for each category (already using criteria system)
    const volumeScore = calculateCategoryScore(
      volumeMetrics.map((m) => m.score) // Each score from evaluateCriteria()
    );
    const frequencyScore = calculateCategoryScore(
      frequencyMetrics.map((m) => m.score) // Each score from evaluateCriteria()
    );
    const exerciseBalanceScore = exerciseBalance.score; // Score from evaluateCriteria()

    // Calculate recovery score based on consecutiveDays criteria
    // Only include muscles that are actually trained (timesPerWeek > 0)
    const recoveryScores = recoveryMetrics.muscleRecovery
      .filter((r) => {
        const freq = frequencyMetrics.find((f) => f.muscle === r.muscle);
        return freq && freq.timesPerWeek > 0 && r.consecutiveDays;
      })
      .map((r) => r.score); // Use score from criteria evaluation

    const recoveryScore = calculateCategoryScore(recoveryScores);

    // Calculate weighted total program score
    // These weights determine the importance of each category in the overall score
    const totalScore =
      volumeScore * 0.4 + // Volume: 35% importance
      frequencyScore * 0.2 + // Frequency: 25% importance
      recoveryScore * 0.2 + // Recovery: 20% importance
      exerciseBalanceScore * 0.2; // Exercise Balance: 20% importance

    const grade = getGrade(totalScore);

    // Build muscle-centric metrics
    const muscleMetrics: MuscleDetailedMetrics[] = volumeMetrics.map((v) => {
      const freq = frequencyMetrics.find((f) => f.muscle === v.muscle);
      const intensity = intensityMetrics.find((i) => i.muscle === v.muscle);
      const recovery = recoveryMetrics.muscleRecovery.find(
        (r) => r.muscle === v.muscle
      );

      /**
       * RECOMMENDATIONS FROM CRITERIA SYSTEM
       *
       * Recommendations are automatically generated by the criteria evaluators.
       * Each criterion can provide a recommendation when its score is below optimal.
       *
       * For example, in frequency-criteria.ts:
       * - evaluateBaseFrequency: Recommends adding more sessions if frequency is low
       * - evaluateConsecutiveDays: Warns about consecutive training days
       *
       * The primary recommendation (lowest scoring criterion) is returned by the hook.
       * Here we aggregate all recommendations for comprehensive muscle insights.
       */

      const recommendations: MuscleRecommendation[] = [];

      // Volume recommendations (from evaluateBaseVolume)
      if (v.recommendation) {
        recommendations.push({
          category: "volume",
          message: v.recommendation,
          priority: getPriority(v.score),
        });
      }

      // Frequency recommendations (from evaluateBaseFrequency)
      if (freq?.recommendation) {
        recommendations.push({
          category: "frequency",
          message: freq.recommendation,
          priority: getPriority(freq.score),
        });
      }

      // Recovery recommendations (from evaluateConsecutiveDays criterion in recovery)
      // Only show recovery recommendations if the muscle is actually trained
      if (recovery?.consecutiveDays && freq && freq.timesPerWeek > 0) {
        if (recovery.consecutiveDays.status === InsightStatus.Warning) {
          recommendations.push({
            category: "recovery",
            message: `This muscle is trained on consecutive days (${recovery.consecutiveDays.minRestDays} rest days). Allow at least 48h between sessions for optimal recovery.`,
            priority: "high",
          });
        } else if (recovery.consecutiveDays.status === InsightStatus.Good) {
          recommendations.push({
            category: "recovery",
            message: `Only ${recovery.consecutiveDays.minRestDays} rest day between sessions. Consider adding one more rest day for optimal recovery.`,
            priority: "medium",
          });
        }
      }

      return {
        muscle: v.muscle,
        volume: {
          setsPerWeek: v.setsPerWeek,
          score: v.score,
          status: getStatus(v.score),
          minRecommended: v.minRecommended,
          maxRecommended: v.maxRecommended,
        },
        frequency: {
          timesPerWeek: freq?.timesPerWeek || 0,
          score: freq?.score || 0,
          status: getStatus(freq?.score || 0),
          dayIndices: freq?.dayIndices || [],
        },
        intensity: intensity
          ? {
              avgRpe: intensity.avgRpe,
            }
          : undefined,
        recovery: recovery
          ? {
              avgRestDays: recovery.avgRestDays,
              consecutiveDays: recovery.consecutiveDays,
            }
          : undefined,
        recommendations,
      };
    });

    // Build exercise metrics
    const exerciseMetrics: ExerciseMetrics = {
      compoundIsolationRatio: {
        compound: Math.round(
          (exerciseBalance.compoundPercentage / 100) *
            exerciseBalance.totalExercises
        ),
        isolation: Math.round(
          (exerciseBalance.isolationPercentage / 100) *
            exerciseBalance.totalExercises
        ),
        compoundPercentage: exerciseBalance.compoundPercentage,
        isolationPercentage: exerciseBalance.isolationPercentage,
        score: exerciseBalance.score,
        status: getStatus(exerciseBalance.score),
        recommendations: exerciseBalance.recommendation
          ? [exerciseBalance.recommendation]
          : [],
      },
      totalExercises: exerciseBalance.totalExercises,
      uniqueExercises: exerciseBalance.uniqueExercises,
    };

    return {
      totalScore: Math.round(totalScore),
      maxTotalScore: 100,
      grade,
      muscleMetrics,
      exerciseMetrics,
      recovery: {
        totalRestDays: recoveryMetrics.totalRestDays,
        totalTrainingDays: recoveryMetrics.totalTrainingDays,
        restDayDistribution: [], // TODO: Calculate rest day distribution
      },
      intensityTechniques: {
        percentage: intensityTechniques.percentage,
        totalExercises: intensityTechniques.totalExercises,
        circuitExercises: intensityTechniques.circuitExercises,
        circuitsByType: intensityTechniques.circuitsByType,
      },
    };
  }, [
    volumeMetrics,
    frequencyMetrics,
    exerciseBalance,
    intensityMetrics,
    recoveryMetrics,
    intensityTechniques,
  ]);
};
